import fs from 'node:fs';
import path from 'node:path';
import assert from 'node:assert/strict';
import { fileURLToPath } from 'node:url';
const here=path.dirname(fileURLToPath(import.meta.url));
const root=path.resolve(here,'..');
const pkg=JSON.parse(fs.readFileSync(path.join(root,'package.json'),'utf8'));
const app=fs.readFileSync(path.join(root,'src/app.js'),'utf8');
const css=fs.readFileSync(path.join(root,'styles.css'),'utf8');
const visuals=fs.readFileSync(path.join(root,'src/visuals.js'),'utf8');
assert.equal(pkg.version,'2.99.0');
assert(app.includes("const APP_VERSION = '2.99'"));
assert(app.includes('topbar-main-row') && app.includes('topbar-sim-row'));
assert(app.includes('club-page-actions'));
assert(!app.includes("pageHead('CLUB CHRONICLE',club.name"));
assert(css.includes('v2.99 layout + club + rarity polish'));
assert(visuals.includes("'Botafogo':'https://assets.football-logos.cc"));
assert(visuals.includes("'Anderlecht':'rsc-anderlecht'"));
console.log(JSON.stringify({version:pkg.version,topbar:'two-row',clubHeader:'single',faces:'preserved'},null,2));
