import fs from 'node:fs';
import path from 'node:path';
import assert from 'node:assert/strict';
import { fileURLToPath } from 'node:url';
import { createWorld } from '../src/engine.js';
import { playerPortrait, coachPortrait } from '../src/visuals.js';
const here = path.dirname(fileURLToPath(import.meta.url));
const root = path.resolve(here, '..');
const packageJson = JSON.parse(fs.readFileSync(path.join(root, 'package.json'), 'utf8'));
const appSource = fs.readFileSync(path.join(root, 'src', 'app.js'), 'utf8');
const styleSource = fs.readFileSync(path.join(root, 'styles.css'), 'utf8');
assert.equal(packageJson.version, '2.97.0');
assert(appSource.includes("const APP_VERSION = '2.97'"));
assert(styleSource.includes('v2.97 portrait cleanup pass'));
const state = createWorld(2970);
const player = state.players[0];
const coach = state.coaches[0];
assert(playerPortrait(player, player.nationalityName || player.nationality, 'xl').includes('assets/faces/players/'));
assert(coachPortrait(coach, coach.nationalityName || coach.nationality, 'xl').includes('assets/faces/coaches/'));
console.log(JSON.stringify({ version: packageJson.version, portraitCleanup: true }, null, 2));
