export const START_SEASON = 2026;
export const SAVE_KEY = 'football-world-chronicle-v2';

export const REGION_ORDER = ['Europe', 'South America', 'North America', 'Asia', 'Africa'];
export const PRIORITY_COUNTRIES = ['Spain', 'England', 'Italy', 'Germany', 'France', 'Portugal', 'Netherlands', 'Brazil', 'Argentina', 'United States', 'Mexico', 'Saudi Arabia', 'Japan'];

export const COUNTRY_META = {
  Spain: { code: 'esp', flag: '🇪🇸', region: 'Europe' }, England: { code: 'eng', flag: '🏴', region: 'Europe' }, Italy: { code: 'ita', flag: '🇮🇹', region: 'Europe' }, Germany: { code: 'ger', flag: '🇩🇪', region: 'Europe' }, France: { code: 'fra', flag: '🇫🇷', region: 'Europe' }, Portugal: { code: 'por', flag: '🇵🇹', region: 'Europe' }, Netherlands: { code: 'ned', flag: '🇳🇱', region: 'Europe' }, Belgium: { code: 'bel', flag: '🇧🇪', region: 'Europe' }, Scotland: { code: 'sco', flag: '🏴', region: 'Europe' }, Türkiye: { code: 'tur', flag: '🇹🇷', region: 'Europe' }, Brazil: { code: 'bra', flag: '🇧🇷', region: 'South America' }, Argentina: { code: 'arg', flag: '🇦🇷', region: 'South America' }, Mexico: { code: 'mex', flag: '🇲🇽', region: 'North America' }, 'United States': { code: 'usa', flag: '🇺🇸', region: 'North America' }, 'Saudi Arabia': { code: 'ksa', flag: '🇸🇦', region: 'Asia' }, Japan: { code: 'jpn', flag: '🇯🇵', region: 'Asia' }, Morocco: { code: 'mar', flag: '🇲🇦', region: 'Africa' }, Egypt: { code: 'egy', flag: '🇪🇬', region: 'Africa' }
};

export const LEAGUE_DEFINITIONS = [
  { id:'ESP1', name:'La Liga', country:'Spain', tier:'detailed', confederation:'Europe', cupName:'Copa del Rey', superCupName:'Spanish Super Cup', clubs:[
    ['real-madrid','Real Madrid','Madrid',92],['barcelona','Barcelona','Barcelona',90],['atletico','Atlético Madrid','Madrid',86],['athletic','Athletic Club','Bilbao',81],['villarreal','Villarreal','Villarreal',80],['real-sociedad','Real Sociedad','San Sebastián',80],['betis','Real Betis','Seville',78],['sevilla','Sevilla','Seville',77],['valencia','Valencia','Valencia',77],['girona','Girona','Girona',76],['celta','Celta Vigo','Vigo',73],['osasuna','Osasuna','Pamplona',73],['mallorca','Mallorca','Palma',72],['getafe','Getafe','Getafe',71],['rayo','Rayo Vallecano','Madrid',70],['alaves','Alavés','Vitoria',69],['espanyol','Espanyol','Barcelona',69],['las-palmas','Las Palmas','Las Palmas',68],['levante','Levante','Valencia',67],['oviedo','Real Oviedo','Oviedo',66]
  ]},
  { id:'ENG1', name:'Premier League', country:'England', tier:'detailed', confederation:'Europe', cupName:'FA Cup', clubs:[
    ['man-city','Manchester City','Manchester',91],['arsenal','Arsenal','London',89],['liverpool','Liverpool','Liverpool',89],['chelsea','Chelsea','London',85],['man-utd','Manchester United','Manchester',83],['tottenham','Tottenham','London',82],['newcastle','Newcastle United','Newcastle',81],['aston-villa','Aston Villa','Birmingham',80],['brighton','Brighton','Brighton',76],['west-ham','West Ham','London',75],['crystal-palace','Crystal Palace','London',75],['fulham','Fulham','London',74],['brentford','Brentford','London',74],['everton','Everton','Liverpool',73],['wolves','Wolverhampton','Wolverhampton',72],['bournemouth','Bournemouth','Bournemouth',72],['nottingham','Nottingham Forest','Nottingham',71],['leeds','Leeds United','Leeds',70],['burnley','Burnley','Burnley',68],['sunderland','Sunderland','Sunderland',67]
  ]},
  { id:'ITA1', name:'Serie A', country:'Italy', tier:'detailed', confederation:'Europe', cupName:'Coppa Italia', clubs:[
    ['inter','Inter','Milan',88],['juventus','Juventus','Turin',86],['milan','AC Milan','Milan',85],['napoli','Napoli','Naples',84],['atalanta','Atalanta','Bergamo',83],['roma','Roma','Rome',81],['lazio','Lazio','Rome',79],['fiorentina','Fiorentina','Florence',78],['bologna','Bologna','Bologna',77],['torino','Torino','Turin',73],['como','Como','Como',73],['udinese','Udinese','Udine',71],['genoa','Genoa','Genoa',71],['parma','Parma','Parma',70],['cagliari','Cagliari','Cagliari',69],['lecce','Lecce','Lecce',68],['verona','Hellas Verona','Verona',68],['sassuolo','Sassuolo','Sassuolo',68],['pisa','Pisa','Pisa',66],['cremonese','Cremonese','Cremona',66]
  ]},
  { id:'GER1', name:'Bundesliga', country:'Germany', tier:'detailed', confederation:'Europe', cupName:'DFB-Pokal', clubs:[
    ['bayern','Bayern Munich','Munich',91],['leverkusen','Bayer Leverkusen','Leverkusen',87],['dortmund','Borussia Dortmund','Dortmund',85],['leipzig','RB Leipzig','Leipzig',83],['frankfurt','Eintracht Frankfurt','Frankfurt',79],['stuttgart','Stuttgart','Stuttgart',79],['wolfsburg','Wolfsburg','Wolfsburg',75],['gladbach','Borussia Mönchengladbach','Mönchengladbach',74],['freiburg','Freiburg','Freiburg',74],['werder','Werder Bremen','Bremen',72],['hoffenheim','Hoffenheim','Sinsheim',72],['mainz','Mainz','Mainz',72],['augsburg','Augsburg','Augsburg',70],['union-berlin','Union Berlin','Berlin',70],['st-pauli','St. Pauli','Hamburg',69],['hamburg','Hamburg','Hamburg',69],['heidenheim','Heidenheim','Heidenheim',67],['koln','Köln','Cologne',68]
  ]},
  { id:'FRA1', name:'Ligue 1', country:'France', tier:'detailed', confederation:'Europe', cupName:'Coupe de France', clubs:[
    ['psg','Paris Saint-Germain','Paris',91],['marseille','Marseille','Marseille',82],['monaco','Monaco','Monaco',82],['lyon','Lyon','Lyon',79],['lille','Lille','Lille',79],['nice','Nice','Nice',78],['lens','Lens','Lens',77],['rennes','Rennes','Rennes',76],['strasbourg','Strasbourg','Strasbourg',74],['nantes','Nantes','Nantes',71],['brest','Brest','Brest',73],['toulouse','Toulouse','Toulouse',72],['auxerre','Auxerre','Auxerre',69],['angers','Angers','Angers',68],['le-havre','Le Havre','Le Havre',67],['lorient','Lorient','Lorient',68],['metz','Metz','Metz',66],['paris-fc','Paris FC','Paris',68]
  ]},
  { id:'POR1', name:'Primeira Liga', country:'Portugal', tier:'detailed', confederation:'Europe', cupName:'Taça de Portugal', clubs:[
    ['benfica','Benfica','Lisbon',84],['porto','Porto','Porto',84],['sporting','Sporting CP','Lisbon',84],['braga','Braga','Braga',78],['vitoria','Vitória SC','Guimarães',73],['famalicao','Famalicão','Famalicão',70],['boavista','Boavista','Porto',69],['estoril','Estoril','Estoril',68],['rio-ave','Rio Ave','Vila do Conde',68],['gil-vicente','Gil Vicente','Barcelos',67],['casa-pia','Casa Pia','Lisbon',67],['moreirense','Moreirense','Moreira de Cónegos',68],['nacional','Nacional','Funchal',66],['arouca','Arouca','Arouca',68],['santa-clara','Santa Clara','Ponta Delgada',67],['estrela','Estrela Amadora','Amadora',65],['farense','Farense','Faro',65],['avs','AVS','Vila das Aves',64]
  ]},
  { id:'NED1', name:'Eredivisie', country:'Netherlands', tier:'condensed', confederation:'Europe', cupName:'KNVB Cup', clubs:[['ajax','Ajax','Amsterdam',81],['psv','PSV','Eindhoven',83],['feyenoord','Feyenoord','Rotterdam',82],['az','AZ Alkmaar','Alkmaar',77],['twente','Twente','Enschede',76],['utrecht','Utrecht','Utrecht',74],['heerenveen','Heerenveen','Heerenveen',70],['groningen','Groningen','Groningen',69],['nec','NEC','Nijmegen',69],['sparta','Sparta Rotterdam','Rotterdam',68]] },
  { id:'BEL1', name:'Belgian Pro League', country:'Belgium', tier:'condensed', confederation:'Europe', cupName:'Belgian Cup', clubs:[['club-brugge','Club Brugge','Bruges',80],['anderlecht','Anderlecht','Brussels',77],['genk','Genk','Genk',77],['gent','Gent','Ghent',75],['union-sg','Union Saint-Gilloise','Brussels',79],['antwerp','Royal Antwerp','Antwerp',75],['standard','Standard Liège','Liège',71],['mechelen','Mechelen','Mechelen',69],['charleroi','Charleroi','Charleroi',68],['cercle-brugge','Cercle Brugge','Bruges',68]] },
  { id:'SCO1', name:'Scottish Premiership', country:'Scotland', tier:'condensed', confederation:'Europe', cupName:'Scottish Cup', clubs:[['celtic','Celtic','Glasgow',79],['rangers','Rangers','Glasgow',78],['aberdeen','Aberdeen','Aberdeen',71],['hearts','Hearts','Edinburgh',71],['hibernian','Hibernian','Edinburgh',69],['dundee-utd','Dundee United','Dundee',67],['motherwell','Motherwell','Motherwell',67],['st-mirren','St Mirren','Paisley',66],['kilmarnock','Kilmarnock','Kilmarnock',66],['dundee','Dundee','Dundee',65]] },
  { id:'TUR1', name:'Süper Lig', country:'Türkiye', tier:'condensed', confederation:'Europe', cupName:'Turkish Cup', clubs:[['galatasaray','Galatasaray','Istanbul',82],['fenerbahce','Fenerbahçe','Istanbul',81],['besiktas','Beşiktaş','Istanbul',77],['trabzonspor','Trabzonspor','Trabzon',75],['basaksehir','Başakşehir','Istanbul',72],['samsunspor','Samsunspor','Samsun',70],['goztepe','Göztepe','Izmir',69],['konyaspor','Konyaspor','Konya',68],['rizespor','Rizespor','Rize',67],['kasimpasa','Kasımpaşa','Istanbul',67]] },
  { id:'BRA1', name:'Brasileirão', country:'Brazil', tier:'condensed', confederation:'South America', cupName:'Copa do Brasil', clubs:[['flamengo','Flamengo','Rio de Janeiro',84],['palmeiras','Palmeiras','São Paulo',84],['botafogo','Botafogo','Rio de Janeiro',81],['fluminense','Fluminense','Rio de Janeiro',79],['sao-paulo','São Paulo','São Paulo',79],['corinthians','Corinthians','São Paulo',78],['gremio','Grêmio','Porto Alegre',77],['internacional','Internacional','Porto Alegre',77],['atletico-mg','Atlético Mineiro','Belo Horizonte',80],['cruzeiro','Cruzeiro','Belo Horizonte',76],['santos','Santos','Santos',75],['bahia','Bahia','Salvador',73]] },
  { id:'ARG1', name:'Liga Profesional', country:'Argentina', tier:'condensed', confederation:'South America', cupName:'Copa Argentina', clubs:[['river','River Plate','Buenos Aires',83],['boca','Boca Juniors','Buenos Aires',82],['racing','Racing Club','Avellaneda',78],['independiente','Independiente','Avellaneda',76],['san-lorenzo','San Lorenzo','Buenos Aires',75],['velez','Vélez Sarsfield','Buenos Aires',76],['estudiantes','Estudiantes','La Plata',76],['talleres','Talleres','Córdoba',75],['rosario-central','Rosario Central','Rosario',73],['newells',"Newell's Old Boys",'Rosario',72],['lanus','Lanús','Lanús',72],['argentinos','Argentinos Juniors','Buenos Aires',72]] },
  { id:'MEX1', name:'Liga MX', country:'Mexico', tier:'condensed', confederation:'North America', cupName:'Copa México', clubs:[['america','Club América','Mexico City',79],['tigres','Tigres UANL','Monterrey',78],['monterrey','Monterrey','Monterrey',78],['cruz-azul','Cruz Azul','Mexico City',77],['chivas','Guadalajara','Guadalajara',75],['pumas','Pumas UNAM','Mexico City',73],['toluca','Toluca','Toluca',75],['pachuca','Pachuca','Pachuca',74],['leon','León','León',72],['santos-laguna','Santos Laguna','Torreón',71]] },
  { id:'USA1', name:'Major League Soccer', country:'United States', tier:'condensed', confederation:'North America', cupName:'U.S. Open Cup', clubs:[['inter-miami','Inter Miami','Miami',78],['lafc','Los Angeles FC','Los Angeles',76],['la-galaxy','LA Galaxy','Los Angeles',75],['seattle','Seattle Sounders','Seattle',74],['atlanta','Atlanta United','Atlanta',72],['nycfc','New York City FC','New York',72],['ny-red-bulls','New York Red Bulls','Harrison',71],['columbus','Columbus Crew','Columbus',74],['portland','Portland Timbers','Portland',70],['austin','Austin FC','Austin',69],['cincinnati','FC Cincinnati','Cincinnati',73],['orlando','Orlando City','Orlando',71]] },
  { id:'KSA1', name:'Saudi Pro League', country:'Saudi Arabia', tier:'condensed', confederation:'Asia', cupName:"King's Cup", clubs:[['al-hilal','Al Hilal','Riyadh',82],['al-nassr','Al Nassr','Riyadh',80],['al-ittihad','Al Ittihad','Jeddah',79],['al-ahli','Al Ahli','Jeddah',78],['al-qadsiah','Al Qadsiah','Khobar',75],['al-shabab','Al Shabab','Riyadh',72],['al-ettifaq','Al Ettifaq','Dammam',71],['al-taawoun','Al Taawoun','Buraidah',70],['al-fateh','Al Fateh','Al-Hasa',68],['al-fayha','Al Fayha','Al Majmaah',67]] },
  { id:'JPN1', name:'J1 League', country:'Japan', tier:'condensed', confederation:'Asia', cupName:"Emperor's Cup", clubs:[['kawasaki','Kawasaki Frontale','Kawasaki',74],['yokohama','Yokohama F. Marinos','Yokohama',74],['kobe','Vissel Kobe','Kobe',75],['urawa','Urawa Red Diamonds','Saitama',73],['kashima','Kashima Antlers','Kashima',73],['hiroshima','Sanfrecce Hiroshima','Hiroshima',74],['gamba','Gamba Osaka','Suita',70],['cerezo','Cerezo Osaka','Osaka',70],['tokyo','FC Tokyo','Tokyo',69],['nagoya','Nagoya Grampus','Nagoya',70]] },
  { id:'MAR1', name:'Botola Pro', country:'Morocco', tier:'condensed', confederation:'Africa', cupName:'Moroccan Throne Cup', clubs:[['wydad','Wydad Casablanca','Casablanca',75],['raja','Raja Casablanca','Casablanca',75],['far-rabat','FAR Rabat','Rabat',74],['rs-berkane','RS Berkane','Berkane',74],['fus-rabat','FUS Rabat','Rabat',69],['mas-fez','MAS Fès','Fès',68],['hassania','Hassania Agadir','Agadir',67],['moghreb-tetouan','Moghreb Tétouan','Tétouan',66]] },
  { id:'EGY1', name:'Egyptian Premier League', country:'Egypt', tier:'condensed', confederation:'Africa', cupName:'Egypt Cup', clubs:[['al-ahly','Al Ahly','Cairo',79],['zamalek','Zamalek','Giza',75],['pyramids','Pyramids FC','Cairo',76],['ismaily','Ismaily','Ismailia',69],['al-masry','Al Masry','Port Said',69],['ceramica','Ceramica Cleopatra','Giza',68],['smouha','Smouha','Alexandria',67],['enppi','ENPPI','Cairo',66]] }
];

export const NATIONAL_TEAMS = [
  ['esp','Spain',90,'Europe'],['eng','England',89,'Europe'],['fra','France',90,'Europe'],['ger','Germany',86,'Europe'],['ita','Italy',85,'Europe'],['por','Portugal',87,'Europe'],['ned','Netherlands',85,'Europe'],['bel','Belgium',82,'Europe'],['cro','Croatia',81,'Europe'],['den','Denmark',80,'Europe'],['sui','Switzerland',80,'Europe'],['tur','Türkiye',79,'Europe'],['sco','Scotland',77,'Europe'],['aut','Austria',79,'Europe'],['srb','Serbia',78,'Europe'],['nor','Norway',80,'Europe'],
  ['bra','Brazil',91,'South America'],['arg','Argentina',91,'South America'],['uru','Uruguay',84,'South America'],['col','Colombia',83,'South America'],['chi','Chile',78,'South America'],['ecu','Ecuador',80,'South America'],['par','Paraguay',76,'South America'],['per','Peru',74,'South America'],['ven','Venezuela',73,'South America'],['bol','Bolivia',68,'South America'],
  ['mex','Mexico',81,'North America'],['usa','United States',80,'North America'],['can','Canada',78,'North America'],['crc','Costa Rica',74,'North America'],['pan','Panama',73,'North America'],['jam','Jamaica',72,'North America'],
  ['jpn','Japan',82,'Asia'],['kor','South Korea',81,'Asia'],['ksa','Saudi Arabia',76,'Asia'],['aus','Australia',78,'Asia'],['irn','Iran',79,'Asia'],['qat','Qatar',73,'Asia'],['chn','China',68,'Asia'],['uzb','Uzbekistan',72,'Asia'],
  ['mar','Morocco',83,'Africa'],['egy','Egypt',78,'Africa'],['sen','Senegal',82,'Africa'],['nga','Nigeria',81,'Africa'],['civ','Ivory Coast',80,'Africa'],['alg','Algeria',79,'Africa'],['gha','Ghana',77,'Africa'],['rsa','South Africa',72,'Africa']
];

const sharedSpanish={first:['Alejandro','Mateo','Hugo','Daniel','Álvaro','Martín','Pablo','Sergio','Adrián','Nico','Iker','David','Marco','Raúl','Javier','Mario','Diego','Rubén','Iván','Gonzalo'],last:['García','Fernández','Navarro','Romero','Serrano','Molina','Ortega','Vega','Paredes','Cabrera','Santos','Méndez','Lorenzo','Prieto','Castillo','Ramos','Suárez','Iglesias','Campos','Rey']};
const sharedEnglish={first:['Jack','Harry','Lewis','Oliver','Charlie','George','James','Callum','Ben','Ethan','Noah','Mason','Ryan','Luke','Adam','Sam','Theo','Jacob'],last:['Walker','Bennett','Hughes','Cooper','Foster','Reed','Morgan','Palmer','Clarke','Ward','Brooks','Turner','Harrison','Cole','Grant','Murray','Pearce','Stone']};
export const NAME_POOLS={
  Spain:sharedSpanish,England:sharedEnglish,Scotland:sharedEnglish,'United States':sharedEnglish,Mexico:sharedSpanish,
  Argentina:{first:['Santiago','Lautaro','Julián','Franco','Facundo','Matías','Thiago','Nicolás','Valentín','Emiliano','Agustín','Tomás'],last:['Fernández','González','Martínez','Álvarez','Acosta','Pereyra','Sosa','Benítez','Quiroga','Roldán','Medina','Vera']},
  Brazil:{first:['João','Gabriel','Lucas','Pedro','Rafael','Matheus','Vinícius','Bruno','Caio','Guilherme','André','Thiago'],last:['Silva','Santos','Oliveira','Souza','Costa','Pereira','Almeida','Ferreira','Rodrigues','Gomes','Barbosa','Moura']},
  Italy:{first:['Luca','Matteo','Marco','Andrea','Davide','Simone','Federico','Niccolò','Alessio','Tommaso','Riccardo','Gabriele','Lorenzo','Pietro','Edoardo'],last:['Bianchi','Romano','Conti','Ferrari','Esposito','Moretti','Rinaldi','Gallo','Greco','Marino','Lombardi','De Luca','Vitale','Serra','Caruso']},
  Germany:{first:['Lukas','Jonas','Leon','Felix','Florian','Maximilian','Julian','Niklas','David','Tobias','Moritz','Kai','Nico','Tim','Sebastian'],last:['Schneider','Weber','Wagner','Becker','Hoffmann','Schäfer','Koch','Bauer','Richter','Klein','Wolf','Neumann','Schwarz','Krüger','Hartmann']},
  France:{first:['Lucas','Hugo','Théo','Nathan','Mathis','Enzo','Raphaël','Antoine','Maxime','Alexandre','Jules','Noé','Yanis','Rayan','Malo'],last:['Martin','Bernard','Dubois','Thomas','Robert','Richard','Petit','Durand','Leroy','Moreau','Simon','Laurent','Michel','Garcia','Roux']},
  Portugal:{first:['João','Tiago','Diogo','Gonçalo','Rui','Miguel','Pedro','Nuno','André','Bruno','Tomás','Duarte','Afonso','Ricardo','Vasco'],last:['Silva','Santos','Ferreira','Pereira','Oliveira','Costa','Rodrigues','Martins','Sousa','Fernandes','Gomes','Lopes','Marques','Alves','Ribeiro']},
  Netherlands:{first:['Daan','Sem','Lars','Finn','Milan','Bram','Jesse','Thijs','Luuk','Noud','Mees','Sven'],last:['de Jong','van Dijk','Jansen','Bakker','Visser','Smit','Meijer','de Boer','Mulder','Bos','Vos','Dekker']},
  Belgium:{first:['Arthur','Louis','Jules','Mathis','Victor','Noah','Milan','Thomas','Nathan','Baptiste'],last:['Peeters','Janssens','Maes','Jacobs','Mertens','Willems','Claes','Goossens','Wouters','Vermeulen']},
  Türkiye:{first:['Emir','Arda','Kerem','Mert','Burak','Ozan','Hakan','Can','Efe','Barış','Yusuf','Kaan'],last:['Yılmaz','Kaya','Demir','Şahin','Çelik','Aydın','Arslan','Koç','Kurt','Öztürk','Aksoy','Güneş']},
  'Saudi Arabia':{first:['Fahad','Salem','Saud','Abdullah','Nasser','Khalid','Yasir','Mohammed','Omar','Hassan'],last:['Al-Dawsari','Al-Qahtani','Al-Harbi','Al-Shammari','Al-Ghamdi','Al-Otaibi','Al-Shehri','Al-Faraj','Al-Buraikan','Al-Najdi']},
  Japan:{first:['Haruto','Ren','Yuto','Sota','Kaito','Riku','Daiki','Takumi','Shota','Hiroto','Ryota','Kenta'],last:['Sato','Suzuki','Takahashi','Tanaka','Watanabe','Ito','Yamamoto','Nakamura','Kobayashi','Kato','Yoshida','Yamada']},
  Morocco:{first:['Youssef','Achraf','Amine','Hakim','Sofiane','Bilal','Ilyas','Anas','Mehdi','Oussama'],last:['El Amrani','Benali','Alaoui','Bennani','Idrissi','Tazi','Berrada','Mansouri','Chafai','Ziani']},
  Egypt:{first:['Omar','Ahmed','Mohamed','Mostafa','Mahmoud','Karim','Youssef','Tarek','Hassan','Amr'],last:['Hassan','Ibrahim','Mahmoud','El Sayed','Fathy','Ashour','Gaber','Hamdy','Kamal','Farouk']}
};

export const POSITION_BLUEPRINT=[{position:'GK',role:'goalkeeper'},{position:'DF',role:'centre back'},{position:'DF',role:'full back'},{position:'MF',role:'deep playmaker'},{position:'MF',role:'attacking midfielder'},{position:'FW',role:'inside forward'},{position:'FW',role:'striker'}];
